import {Cartoons} from './cartoon'

export const CARTOON:Cartoons[]=[
    {
        name:'Clannad',
        author:"Key",
        type:"治愈系",
        episodes:24,
        comment:'无',
        num:1
    },
    {
        name:'未闻花名',
        author:"长井龙雪",
        type:"治愈系",
        episodes:11,
        comment:'无',
        num:2
    },
    {
        name:'Anglebeat',
        author:"岸诚二",
        type:"治愈系",
        episodes:13,
        comment:'无',
        num:3
    },
    {
        name:'工作细胞',
        author:"清水茜",
        type:"搞笑",
        episodes:14,
        comment:'无',
        num:4
    },
    {
        name:'紫罗兰永恒花园',
        author:"石立太一",
        type:"治愈系",
        episodes:13,
        comment:'无',
        num:5
    },
    {
        name:'末日时在做什么？有没有空？可以来拯救吗？',
        author:"枯野瑛",
        type:"治愈系",
        episodes:12,
        comment:'如果回忆有颜色，那一定是被记忆染红的苍蓝',
        num:6
    }
]
